with food_assets (food_name, asset_key) as (
  values
    ('Açaí na tigela', 'acai.webp'),
    ('Acarajé', 'acaraje.webp'),
    ('Arroz carreteiro', 'arroz-carreteiro.webp'),
    ('Baião de dois', 'baiao-de-dois.webp'),
    ('Banoffee', 'banoffe.webp'),
    ('Barreado', 'barreado.webp'),
    ('Beijinho', 'beijinho.webp'),
    ('Bibimbap', 'bibimbap.webp'),
    ('Bobó de camarão', 'bobo-de-camarao.webp'),
    ('Bolo de chocolate', 'bolo-de-chocolate.webp'),
    ('Brigadeiro', 'brigadeiro.webp'),
    ('Brownie', 'brownie.webp'),
    ('Buchada de bode', 'buchada-de-bode.webp'),
    ('Burrito', 'burrito.webp'),
    ('Caldo de sururu', 'caldo-de-sururu.webp'),
    ('Carne de sol com macaxeira', 'carne-de-sol-macaxeira.webp'),
    ('Cartola', 'cartola.webp'),
    ('Ceviche', 'ceviche.webp'),
    ('Cheesecake', 'cheesecake.webp'),
    ('Churrasco', 'churrasco.webp'),
    ('Churros', 'churros.webp'),
    ('Cocada', 'cocada.webp'),
    ('Costela barbecue', 'costela.webp'),
    ('Croque monsieur', 'croque-monsieur.webp'),
    ('Curry indiano', 'curry-indiano.webp'),
    ('Cuscuz com carne de sol', 'cucuz-carne-de-sol.webp'),
    ('Cuscuz nordestino', 'cuscuz.webp'),
    ('Donut', 'donut.webp'),
    ('Escondidinho de carne-seca', 'escodidinho.webp'),
    ('Falafel', 'falafel.webp'),
    ('Feijoada', 'feijoada.webp'),
    ('Fish and chips', 'fish-n-chips.webp'),
    ('Frango assado', 'frango-assado.webp'),
    ('Galinhada', 'galinhada.webp'),
    ('Goulash', 'goulash.webp'),
    ('Gyros', 'gyros.webp'),
    ('Hambúrguer artesanal', 'hamburgue.webp'),
    ('Hot dog', 'hot-dog.webp'),
    ('Kebab', 'kebal.webp'),
    ('Lasanha', 'lasanha.webp'),
    ('Macarronada', 'macarronada.webp'),
    ('Moqueca', 'moqueca.webp'),
    ('Mousse de maracujá', 'mousse-de-maracuja.webp'),
    ('Pad thai', 'pad-thai.webp'),
    ('Paella', 'paella.webp'),
    ('Palha italiana', 'palha-italiana.webp'),
    ('Pão de queijo', 'pao-de-gueijo.webp'),
    ('Parmegiana', 'parmegiana.webp'),
    ('Pastel', 'pastel.webp'),
    ('Pato no tucupi', 'pato-no-tucupi.webp'),
    ('Pavê', 'pave.webp'),
    ('Petit gâteau', 'petii-gateau.webp'),
    ('Pho', 'pho.webp'),
    ('Pizza', 'pizza.webp'),
    ('Pudim de leite', 'pudim-de-leite.webp'),
    ('Ramen', 'ramen.webp'),
    ('Risoto', 'risoto.webp'),
    ('Romeu e Julieta', 'romeu-e-julieta.webp'),
    ('Sorvete', 'sorvete.webp'),
    ('Strogonoff de frango', 'strogonoff.webp'),
    ('Sushi combinado', 'sushi.webp'),
    ('Tacos', 'tacos.webp'),
    ('Tapioca doce', 'tapioca-doce.webp'),
    ('Tapioca recheada', 'tapioca.webp'),
    ('Torta de limão', 'torta-de-limao.webp'),
    ('Tutu de feijão', 'tutu-de-feijao.webp'),
    ('Vatapá', 'vatapa.webp'),
    ('Virado à paulista', 'virado-a-paulista.webp'),
    ('X-tudo', 'x-tudo.webp'),
    ('Yakisoba', 'yakisoba.webp')
)
update public.foods as food
set asset_key = food_assets.asset_key
from food_assets
where food.name = food_assets.food_name;
